package Model;
// Generated 11-11-2014 07:19:28 PM by Hibernate Tools 3.6.0



/**
 * Cuentas generated by hbm2java
 */
public class Cuentas  implements java.io.Serializable {


     private Integer idCuentas;
     private Ejecutivo ejecutivo;
     private String nombre;

    public Cuentas() {
    }

    public Cuentas(Ejecutivo ejecutivo, String nombre) {
       this.ejecutivo = ejecutivo;
       this.nombre = nombre;
    }
   
    public Integer getIdCuentas() {
        return this.idCuentas;
    }
    
    public void setIdCuentas(Integer idCuentas) {
        this.idCuentas = idCuentas;
    }
    public Ejecutivo getEjecutivo() {
        return this.ejecutivo;
    }
    
    public void setEjecutivo(Ejecutivo ejecutivo) {
        this.ejecutivo = ejecutivo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


