package Model;
// Generated 11-11-2014 07:19:28 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ejecutivo generated by hbm2java
 */
public class Ejecutivo  implements java.io.Serializable {


     private Integer idEjecutivo;
     private Equipo equipo;
     private String nombre;
     private String rut;
     private String email;
     private String telefono;
     private Date fechaIngreso;
     private Set<Cuentas> cuentases = new HashSet<Cuentas>(0);

    public Ejecutivo() {
    }

	
    public Ejecutivo(Equipo equipo, String nombre) {
        this.equipo = equipo;
        this.nombre = nombre;
    }
    public Ejecutivo(Equipo equipo, String nombre, String rut, String email, String telefono, Date fechaIngreso, Set<Cuentas> cuentases) {
       this.equipo = equipo;
       this.nombre = nombre;
       this.rut = rut;
       this.email = email;
       this.telefono = telefono;
       this.fechaIngreso = fechaIngreso;
       this.cuentases = cuentases;
    }
   
    public Integer getIdEjecutivo() {
        return this.idEjecutivo;
    }
    
    public void setIdEjecutivo(Integer idEjecutivo) {
        this.idEjecutivo = idEjecutivo;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Set<Cuentas> getCuentases() {
        return this.cuentases;
    }
    
    public void setCuentases(Set<Cuentas> cuentases) {
        this.cuentases = cuentases;
    }




}


