package Model;
// Generated 11-11-2014 07:19:28 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer idEquipo;
     private Liga liga;
     private String nombre;
     private Integer puntaje;
     private Set<Ejecutivo> ejecutivos = new HashSet<Ejecutivo>(0);

    public Equipo() {
    }

	
    public Equipo(Liga liga, String nombre) {
        this.liga = liga;
        this.nombre = nombre;
    }
    public Equipo(Liga liga, String nombre, Integer puntaje, Set<Ejecutivo> ejecutivos) {
       this.liga = liga;
       this.nombre = nombre;
       this.puntaje = puntaje;
       this.ejecutivos = ejecutivos;
    }
   
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(Integer puntaje) {
        this.puntaje = puntaje;
    }
    public Set<Ejecutivo> getEjecutivos() {
        return this.ejecutivos;
    }
    
    public void setEjecutivos(Set<Ejecutivo> ejecutivos) {
        this.ejecutivos = ejecutivos;
    }




}


